- hosts: webserver
  become: yes
  tasks:
    - name: update
      yum: update_cache=yes

    - name: Install Nginx
      yum: name=nginx state=latest

      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=reloaded
